### ISSUE TITLE
Структура репозитория

### ISSUE THREAD

**Issue by avasyukov** [IvanOfficial/template_tree#2]
(Тикет-напоминалка. Подробностей здесь нет. Сделать проще вживую.)

**Comment by GerasimovIV** [comment]
привел в нормальный вид

**Comment by avasyukov** [comment]
Но в папке headers не только хэдеры!

Да, я придираюсь. Да, можно бы и забить уже. Но всё же нет - давайте до совсем нормального вида. Назовите её sources, src, tree - всё норм, так как тогда название соответствует содержимому.

**Comment by GerasimovIV** [comment]
сделал
а cmake тоже загружать? или так оставить?

**Comment by avasyukov** [comment]
Если он есть - лучше тоже залить. Сценарий сборки - это хорошо.

**Comment by GerasimovIV** [comment]
добавил cmake

**Comment by avasyukov** [comment]
Да, теперь стало хорошо.
