### ISSUE TITLE
Балансировка

### ISSUE THREAD

**Issue by avasyukov** [IvanOfficial/template_tree#3]
После всех правок балансировке почти хорошо, но не совсем хорошо. Тестовый сценарий:
- создать дерево на 8 элементов, это неизбежно высота 3
- удалить неудобный элемент (корневой, например)
- элементов остаётся 7, они должны уложиться в дерево высоты 2

По факту наблюдается вот такое:
```
Container created
Tree after creation:
Element: 16 Height: 3 Left: 4 Right: 36 
Element: 4 Height: 1 Left: 1 Right: 9 
Element: 1 Height: 0 Left: -- Right: -- 
Element: 9 Height: 0 Left: -- Right: -- 
Element: 36 Height: 2 Left: 25 Right: 49 
Element: 25 Height: 0 Left: -- Right: -- 
Element: 49 Height: 1 Left: -- Right: 64 
Element: 64 Height: 0 Left: -- Right: -- 
Tree after deletion of the element:
Element: 36 Height: 3 Left: 4 Right: 49 
Element: 4 Height: 2 Left: 1 Right: 9 
Element: 1 Height: 0 Left: -- Right: -- 
Element: 9 Height: 1 Left: -- Right: 25 
Element: 25 Height: 0 Left: -- Right: -- 
Element: 49 Height: 1 Left: -- Right: 64 
Element: 64 Height: 0 Left: -- Right: -- 
```

То есть дерево формально корректно. Но баланс потеряло.

**Comment by GerasimovIV** [comment]
вообще да, но по определению полученное дерево является сбалансированным
АВЛ-дерево — сбалансированное по высоте двоичное дерево поиска: для каждой его вершины высота её двух поддеревьев различается не более чем на 1.  Или я тогда не понимаю правило распределения высот по дереву?

**Comment by GerasimovIV** [comment]
А

**Comment by GerasimovIV** [comment]
У меня нет вершины, у которой высоты ее двух поддеревьев отличаются больше чем на 1

**Comment by GerasimovIV** [comment]
а, разницу надо считать, между вершиной и поддеревом, а не между ее поддеревьями

**Comment by GerasimovIV** [comment]
сейчас переделаю

**Comment by avasyukov** [comment]
Ваша реализация корректна. Мои огромные извинения - просто уже рябит в глазах от разных реализаций с разными творческими багами. Но в Вашей реализации багов по балансировке нет.

Тикет закрываю. Добейте #4, и на этом всё.

**Comment by GerasimovIV** [comment]
готово
