### ISSUE TITLE
[Финальный штрих] Утечка памяти при удалении корня

### ISSUE THREAD

**Issue by avasyukov** [IvanOfficial/template_tree#4]
Собственно, сабж - забыли почистить память в этом отдельном случае. Справедливое "фи" от valgrind-а:
```
==31761== 
==31761== HEAP SUMMARY:
==31761==     in use at exit: 24 bytes in 1 blocks
==31761==   total heap usage: 11 allocs, 10 frees, 73,936 bytes allocated
==31761== 
==31761== LEAK SUMMARY:
==31761==    definitely lost: 24 bytes in 1 blocks
==31761==    indirectly lost: 0 bytes in 0 blocks
==31761==      possibly lost: 0 bytes in 0 blocks
==31761==    still reachable: 0 bytes in 0 blocks
==31761==         suppressed: 0 bytes in 0 blocks
==31761== Rerun with --leak-check=full to see details of leaked memory
```

**Comment by GerasimovIV** [comment]
сейчас вернул старую реализацию баланса (у меня появилась еще одно хорошая идея для балансировки, но она требует еще доработок, пока не успеваю её полностью нормально реализовать), и исправил "фи" от valgrind-а :)

**Comment by GerasimovIV** [comment]
единственное, у меня поле  still reachable: не осталось нулевым, это память, которая осталась "доступна" после завершения (не много не понимаю, что это за память)? С ней тоже нужно бороться?

**Comment by avasyukov** [comment]
Да, починено.

Насчёт still reachable - https://stackoverflow.com/questions/3840582/still-reachable-leak-detected-by-valgrind

Если коротко - нет, это фиксить не надо. Это не является утечкой в строгом смысле. Обычно это особенности поведения системных библиотек. Вангую, что в данном случае это какие-то особенности сборки Ubuntu, потому что у меня проход valgrind-а совсем чистый.
